export const actions = {
  // Theme actions
  FETCH_DARKMODE: "FETCH_DARKMODE",
  TOGGLE_DARKMODE: "TOGGLE_DARKMODE",
  // User actions
  FETCH_USER_FROM_COOKIES: "FETCH_USER_FROM_COOKIES",
  AUTH_USER: "AUTH_USER",
  LOGOUT_USER: "LOGOUT_USER",
  UPDATE_USER: "UPDATE_USER",
  // Tasks actions
  FETCH_TASKS: "FETCH_TASKS",
  ADD_TASK: "ADD_TASK",
  DELETE_TASK: "DELETE_TASK",
  UPDATE_TASK_CONTENTS: "UPDATE_TASK_CONTENTS",
  UPDATE_TASK_STATUS: "UPDATE_TASK_STATUS",
};
